/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck

const process = require('node:process');
const path = require('node:path');
const { fileURLToPath } = require('node:url');
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url));

const runtime = require("@prisma/client/runtime/client");
const $Enums = require("./enums.ts");
const $Class = require("./internal/class.ts");
const Prisma = require("./internal/prismaNamespace.ts");

module.exports = {
  ...$Enums,
  PrismaClient: $Class.getPrismaClientClass(),
  Prisma,
  User: Prisma.UserModel,
  Account: Prisma.AccountModel,
  Transaction: Prisma.TransactionModel,
  Budget: Prisma.BudgetModel,
};